# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
