# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0002_auto_20151224_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 24, 5, 32, 46, 770142, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oam.Invoice'),
        ),
    ]
