# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0003_auto_20151224_0532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date_added']},
        ),
    ]
