# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0004_auto_20151224_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(blank=True, verbose_name='Transaction Date'),
        ),
    ]
