# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0005_auto_20151224_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='number',
        ),
    ]
