# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0006_auto_20151225_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
