# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0007_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='Cheque', max_length=30),
        ),
    ]
