# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0008_transaction_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TansactionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_cdn_url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oam.Transaction')),
            ],
        ),
    ]
