# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oam', '0009_tansactionimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TansactionImage',
            new_name='TransactionImage',
        ),
    ]
